apiVersion: apps/v1
kind: Deployment
metadata:
  name: apline-serviceaccount-deployment
  labels:
    app: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      serviceAccountName: platform-demo
      containers:
        - name: apline
          image: byrnedo/alpine-curl
          command:
            - "sh"
            - "-c"
            - "sleep 10000"
